import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export interface SessionToken {
  token: string;
  userId: string;
  moduleName: string;
  expiresAt: Date;
  isAutoGenerated: boolean;
}

export class SessionManager {
  // Générer automatiquement un token d'accès pour un utilisateur connecté
  static async generateAutoToken(userId: string, moduleName: string): Promise<string> {
    const token = crypto.randomUUID();
    const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000); // 24h
    
    // Stocker le token dans Supabase
    await supabase
      .from('auto_tokens')
      .insert({
        token: token,
        user_id: userId,
        module_name: moduleName,
        expires_at: expiresAt.toISOString(),
        is_auto_generated: true,
        created_at: new Date().toISOString()
      });
    
    return token;
  }
  
  // Valider un token automatique
  static async validateAutoToken(token: string, moduleName: string): Promise<SessionToken | null> {
    const { data, error } = await supabase
      .from('auto_tokens')
      .select('*')
      .eq('token', token)
      .eq('module_name', moduleName)
      .eq('is_auto_generated', true)
      .single();
    
    if (error || !data) return null;
    
    const expiresAt = new Date(data.expires_at);
    if (expiresAt < new Date()) return null;
    
    return {
      token: data.token,
      userId: data.user_id,
      moduleName: data.module_name,
      expiresAt: expiresAt,
      isAutoGenerated: true
    };
  }
  
  // Nettoyer les tokens expirés
  static async cleanupExpiredTokens(): Promise<void> {
    await supabase
      .from('auto_tokens')
      .delete()
      .lt('expires_at', new Date().toISOString());
  }
}
