import { createClient } from '@supabase/supabase-js';
import { getSupabaseUrl, getSupabaseServiceRoleKey } from '@/utils/supabaseConfig';

const AUTO_TOKEN_EXPIRES_AT = new Date('2100-01-01T00:00:00.000Z');

const supabase = createClient(
  getSupabaseUrl(),
  getSupabaseServiceRoleKey()
);

export interface SessionToken {
  token: string;
  userId: string;
  moduleName: string;
  expiresAt: Date;
  isAutoGenerated: boolean;
}

export class SessionManager {
  // Générer automatiquement un token d'accès pour un utilisateur connecté
  static async generateAutoToken(userId: string, moduleName: string, userEmail?: string): Promise<string> {
    const token = crypto.randomUUID();
    const expiresAt = AUTO_TOKEN_EXPIRES_AT;
    
    // Stocker le token dans Supabase
    await supabase
      .from('auto_tokens')
      .insert({
        token: token,
        user_id: userId,
        module_name: moduleName,
        expires_at: expiresAt.toISOString(),
        is_auto_generated: true,
        created_at: new Date().toISOString()
      });
    
    return token;
  }
  
  // Valider un token automatique
  static async validateAutoToken(token: string, moduleName: string): Promise<SessionToken | null> {
    const { data, error } = await supabase
      .from('auto_tokens')
      .select('*')
      .eq('token', token)
      .eq('module_name', moduleName)
      .eq('is_auto_generated', true)
      .single();
    
    if (error || !data) return null;

    const expiresAt = new Date(data.expires_at);

    return {
      token: data.token,
      userId: data.user_id,
      moduleName: data.module_name,
      expiresAt: expiresAt,
      isAutoGenerated: true
    };
  }
  
  // Nettoyer les tokens expirés
  static async cleanupExpiredTokens(): Promise<void> {
    await supabase
      .from('auto_tokens')
      .delete()
      .lt('expires_at', new Date().toISOString());
  }
}
