import { createClient } from '@supabase/supabase-js';
import { isAdminUser } from './sessionDurationCheck';

const DEFAULT_TOKEN_DURATION_MS = 24 * 60 * 60 * 1000; // 24h pour admin
const LIMITED_TOKEN_DURATION_MS = 60 * 60 * 1000; // 60 minutes pour utilisateurs normaux

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export interface SessionToken {
  token: string;
  userId: string;
  moduleName: string;
  expiresAt: Date;
  isAutoGenerated: boolean;
}

export class SessionManager {
  // Générer automatiquement un token d'accès pour un utilisateur connecté
  static async generateAutoToken(userId: string, moduleName: string, userEmail?: string): Promise<string> {
    // Déterminer la durée du token selon si l'utilisateur est admin
    let tokenDuration = LIMITED_TOKEN_DURATION_MS; // 60 minutes par défaut
    
    // Si on a l'email, vérifier si c'est l'admin
    if (userEmail && isAdminUser(userEmail)) {
      tokenDuration = DEFAULT_TOKEN_DURATION_MS; // 24h pour admin
    } else if (!userEmail) {
      // Si on n'a pas l'email, essayer de le récupérer depuis la base de données
      try {
        const { data: userData } = await supabase.auth.admin.getUserById(userId);
        if (userData?.user?.email && isAdminUser(userData.user.email)) {
          tokenDuration = DEFAULT_TOKEN_DURATION_MS;
        }
      } catch (error) {
        console.warn('Impossible de récupérer l\'email de l\'utilisateur, utilisation durée limitée');
      }
    }
    
    const token = crypto.randomUUID();
    const expiresAt = new Date(Date.now() + tokenDuration);
    
    // Stocker le token dans Supabase
    await supabase
      .from('auto_tokens')
      .insert({
        token: token,
        user_id: userId,
        module_name: moduleName,
        expires_at: expiresAt.toISOString(),
        is_auto_generated: true,
        created_at: new Date().toISOString()
      });
    
    return token;
  }
  
  // Valider un token automatique
  static async validateAutoToken(token: string, moduleName: string): Promise<SessionToken | null> {
    const { data, error } = await supabase
      .from('auto_tokens')
      .select('*')
      .eq('token', token)
      .eq('module_name', moduleName)
      .eq('is_auto_generated', true)
      .single();
    
    if (error || !data) return null;
    
    const expiresAt = new Date(data.expires_at);
    if (expiresAt < new Date()) return null;
    
    return {
      token: data.token,
      userId: data.user_id,
      moduleName: data.module_name,
      expiresAt: expiresAt,
      isAutoGenerated: true
    };
  }
  
  // Nettoyer les tokens expirés
  static async cleanupExpiredTokens(): Promise<void> {
    await supabase
      .from('auto_tokens')
      .delete()
      .lt('expires_at', new Date().toISOString());
  }
}
