export interface Exercise {
  id: string;
  title: string;
  description: string;
  objective: string;
  difficulty: 'facile' | 'moyen' | 'difficile';
  category: 'variables' | 'boucles' | 'conditions' | 'fonctions' | 'logique';
  icon: string;
  estimatedTime: string;
  ageMin: number;
  ageMax: number;
}

export const exercises: Exercise[] = [
  {
    id: 'variables-1',
    title: 'Les Variables - Mon Premier Nom',
    description: 'Découvre comment stocker et utiliser des informations dans le code !',
    objective: 'Créer une variable qui contient ton prénom et l\'afficher',
    difficulty: 'facile',
    category: 'variables',
    icon: '📝',
    estimatedTime: '5 min',
    ageMin: 6,
    ageMax: 7
  },
  {
    id: 'variables-2',
    title: 'Calculer mon Âge',
    description: 'Utilise des variables pour faire des calculs simples !',
    objective: 'Créer une variable pour ton année de naissance et calculer ton âge',
    difficulty: 'facile',
    category: 'variables',
    icon: '🔢',
    estimatedTime: '7 min',
    ageMin: 8,
    ageMax: 9
  },
  {
    id: 'variables-3',
    title: 'Mon Animal Préféré',
    description: 'Stocke un mot dans une variable et découvre des infos dessus !',
    objective: 'Créer une variable "animal" et afficher un message',
    difficulty: 'facile',
    category: 'variables',
    icon: '🐾',
    estimatedTime: '6 min',
    ageMin: 6,
    ageMax: 7
  },
  {
    id: 'variables-4',
    title: 'Mon Score + Bonus',
    description: 'Fais un calcul simple avec une variable de score !',
    objective: 'Ajouter un bonus à un score',
    difficulty: 'facile',
    category: 'variables',
    icon: '🏆',
    estimatedTime: '7 min',
    ageMin: 7,
    ageMax: 8
  },
  {
    id: 'variables-5',
    title: 'Ma Couleur Préférée',
    description: 'Stocke une couleur et affiche un message rigolo !',
    objective: 'Créer une variable "couleur" et l\'utiliser dans une phrase',
    difficulty: 'facile',
    category: 'variables',
    icon: '🎨',
    estimatedTime: '6 min',
    ageMin: 6,
    ageMax: 7
  },
  {
    id: 'variables-6',
    title: 'Les Mots Magiques',
    description: 'Combine deux mots pour créer une phrase !',
    objective: 'Assembler deux mots avec une variable',
    difficulty: 'facile',
    category: 'variables',
    icon: '✨',
    estimatedTime: '7 min',
    ageMin: 6,
    ageMax: 7
  },
  {
    id: 'boucles-1',
    title: 'Compter jusqu\'à 10',
    description: 'Apprends à répéter des actions avec les boucles !',
    objective: 'Utiliser une boucle pour afficher les nombres de 1 à 10',
    difficulty: 'facile',
    category: 'boucles',
    icon: '🔁',
    estimatedTime: '8 min',
    ageMin: 7,
    ageMax: 8
  },
  {
    id: 'boucles-2',
    title: 'Dessiner avec des Étoiles',
    description: 'Crée des formes en répétant des actions !',
    objective: 'Utiliser une boucle pour dessiner une ligne d\'étoiles',
    difficulty: 'moyen',
    category: 'boucles',
    icon: '⭐',
    estimatedTime: '10 min',
    ageMin: 8,
    ageMax: 9
  },
  {
    id: 'boucles-4',
    title: 'Pixel Art - Damier Emoji',
    description: 'Dessine un damier (comme un échiquier) en utilisant des boucles !',
    objective: 'Créer un damier en alternant 2 emojis dans une double boucle',
    difficulty: 'moyen',
    category: 'boucles',
    icon: '🧱',
    estimatedTime: '12 min',
    ageMin: 10,
    ageMax: 11
  },
  {
    id: 'boucles-5',
    title: 'Mon Mot en Lettres',
    description: 'Affiche chaque lettre de ton mot sur une ligne avec une boucle !',
    objective: 'Utiliser une boucle pour parcourir un mot lettre par lettre',
    difficulty: 'moyen',
    category: 'boucles',
    icon: '🔤',
    estimatedTime: '10 min',
    ageMin: 9,
    ageMax: 10
  },
  {
    id: 'conditions-1',
    title: 'Si... Alors...',
    description: 'Décide ce qui se passe selon les situations !',
    objective: 'Utiliser une condition pour dire "Bonjour" si c\'est le matin',
    difficulty: 'facile',
    category: 'conditions',
    icon: '🤔',
    estimatedTime: '8 min',
    ageMin: 8,
    ageMax: 9
  },
  {
    id: 'conditions-2',
    title: 'Le Jeu des Devinettes',
    description: 'Crée un petit jeu où l\'ordinateur devine !',
    objective: 'Utiliser des conditions pour comparer un nombre deviné',
    difficulty: 'moyen',
    category: 'conditions',
    icon: '🎯',
    estimatedTime: '12 min',
    ageMin: 10,
    ageMax: 11
  },
  {
    id: 'logique-1',
    title: 'Combiner les Conditions',
    description: 'Utilise "ET" et "OU" pour des décisions plus complexes !',
    objective: 'Vérifier si on peut aller au parc (beau temps ET pas de pluie)',
    difficulty: 'moyen',
    category: 'logique',
    icon: '🧩',
    estimatedTime: '10 min',
    ageMin: 11,
    ageMax: 12
  },
  {
    id: 'fonctions-1',
    title: 'Ma Première Fonction',
    description: 'Crée des actions réutilisables !',
    objective: 'Créer une fonction qui dit "Bonjour" avec un prénom',
    difficulty: 'moyen',
    category: 'fonctions',
    icon: '⚙️',
    estimatedTime: '12 min',
    ageMin: 9,
    ageMax: 10
  },
  {
    id: 'fonctions-3',
    title: 'Générateur de Pseudo',
    description: 'Crée un pseudo fun en combinant des mots avec une fonction !',
    objective: 'Écrire une fonction qui combine un prénom + un surnom (ex: "Super Panda")',
    difficulty: 'moyen',
    category: 'fonctions',
    icon: '🪄',
    estimatedTime: '12 min',
    ageMin: 10,
    ageMax: 11
  },
  {
    id: 'fonctions-4',
    title: 'Le Dé Magique',
    description: 'Lance un dé avec une fonction et un peu de hasard !',
    objective: 'Utiliser une fonction pour générer un nombre aléatoire',
    difficulty: 'moyen',
    category: 'fonctions',
    icon: '🎲',
    estimatedTime: '12 min',
    ageMin: 11,
    ageMax: 12
  },
  {
    id: 'boucles-3',
    title: 'La Table de Multiplication',
    description: 'Apprends les tables en programmant !',
    objective: 'Utiliser une boucle pour afficher la table de 5',
    difficulty: 'moyen',
    category: 'boucles',
    icon: '✖️',
    estimatedTime: '10 min',
    ageMin: 9,
    ageMax: 10
  },
  {
    id: 'conditions-3',
    title: 'Le Convertisseur de Notes',
    description: 'Transforme tes notes en lettres !',
    objective: 'Utiliser des conditions pour convertir une note numérique en lettre',
    difficulty: 'moyen',
    category: 'conditions',
    icon: '📊',
    estimatedTime: '12 min',
    ageMin: 11,
    ageMax: 12
  },
  {
    id: 'conditions-4',
    title: 'Le Robot des Réponses',
    description: 'Donne un mot au robot et il choisit la bonne réponse !',
    objective: 'Utiliser des conditions pour réagir selon un mot (bonjour / merci / au revoir...)',
    difficulty: 'facile',
    category: 'conditions',
    icon: '🤖',
    estimatedTime: '8 min',
    ageMin: 7,
    ageMax: 8
  },
  {
    id: 'conditions-5',
    title: 'Le Thermomètre',
    description: 'Selon la température, ton programme décide !',
    objective: 'Utiliser if/else if pour classer une température',
    difficulty: 'moyen',
    category: 'conditions',
    icon: '🌡️',
    estimatedTime: '10 min',
    ageMin: 9,
    ageMax: 10
  },
  {
    id: 'logique-3',
    title: 'Entrer à la Fête',
    description: 'Tu peux entrer si tu as une invitation OU si un parent t\'accompagne !',
    objective: 'Utiliser le OU (||) pour une décision',
    difficulty: 'moyen',
    category: 'logique',
    icon: '🎉',
    estimatedTime: '10 min',
    ageMin: 11,
    ageMax: 12
  },
  {
    id: 'logique-4',
    title: 'Le Mot de Passe',
    description: 'Tu peux entrer si le mot de passe est bon ET si tu as l\'âge minimum !',
    objective: 'Utiliser ET (&&) avec deux conditions',
    difficulty: 'moyen',
    category: 'logique',
    icon: '🔐',
    estimatedTime: '12 min',
    ageMin: 11,
    ageMax: 12
  },
  {
    id: 'logique-2',
    title: 'Le Gardien du Trésor',
    description: 'Protège un trésor avec plusieurs conditions !',
    objective: 'Vérifier plusieurs conditions pour ouvrir un coffre (clé ET code correct)',
    difficulty: 'difficile',
    category: 'logique',
    icon: '🗝️',
    estimatedTime: '15 min',
    ageMin: 12,
    ageMax: 14
  },
  {
    id: 'fonctions-2',
    title: 'La Machine à Calculer',
    description: 'Crée une calculatrice avec des fonctions !',
    objective: 'Créer des fonctions pour additionner, soustraire, multiplier',
    difficulty: 'difficile',
    category: 'fonctions',
    icon: '🧮',
    estimatedTime: '15 min',
    ageMin: 12,
    ageMax: 14
  },
  {
    id: 'complete-1',
    title: 'Complète la Boucle',
    description: 'Complète le code pour afficher les nombres de 1 à 5 !',
    objective: 'Compléter la ligne manquante dans la boucle',
    difficulty: 'facile',
    category: 'boucles',
    icon: '✏️',
    estimatedTime: '8 min',
    ageMin: 7,
    ageMax: 8
  },
  {
    id: 'complete-2',
    title: 'Complète la Condition',
    description: 'Complète la condition pour vérifier l\'âge !',
    objective: 'Compléter la condition manquante',
    difficulty: 'facile',
    category: 'conditions',
    icon: '✏️',
    estimatedTime: '8 min',
    ageMin: 8,
    ageMax: 9
  },
  {
    id: 'complete-3',
    title: 'Complète la Variable',
    description: 'Crée et utilise une variable correctement !',
    objective: 'Compléter la déclaration et l\'utilisation de la variable',
    difficulty: 'facile',
    category: 'variables',
    icon: '✏️',
    estimatedTime: '7 min',
    ageMin: 6,
    ageMax: 7
  },
  {
    id: 'complete-4',
    title: 'Complète la Fonction',
    description: 'Complète la fonction de multiplication !',
    objective: 'Compléter le nom et le calcul de la fonction',
    difficulty: 'moyen',
    category: 'fonctions',
    icon: '✏️',
    estimatedTime: '10 min',
    ageMin: 10,
    ageMax: 11
  },
  {
    id: 'complete-5',
    title: 'Complète le Tableau',
    description: 'Ajoute un nouvel animal dans une liste !',
    objective: 'Compléter la ligne manquante pour ajouter un élément dans un tableau',
    difficulty: 'moyen',
    category: 'variables',
    icon: '✏️',
    estimatedTime: '10 min',
    ageMin: 9,
    ageMax: 10
  },
  {
    id: 'complete-6',
    title: 'Complète l\'Index',
    description: 'Récupère un élément dans un tableau avec [index] !',
    objective: 'Compléter le bon index pour obtenir le bon élément',
    difficulty: 'moyen',
    category: 'variables',
    icon: '✏️',
    estimatedTime: '10 min',
    ageMin: 10,
    ageMax: 11
  },
  {
    id: 'complete-7',
    title: 'Complète l\'Objet',
    description: 'Mets à jour la propriété score d\'un objet joueur !',
    objective: 'Compléter la ligne manquante pour modifier une propriété',
    difficulty: 'difficile',
    category: 'variables',
    icon: '✏️',
    estimatedTime: '12 min',
    ageMin: 12,
    ageMax: 14
  },
  {
    id: 'complete-8',
    title: 'Complète le For + Tableau',
    description: 'Complète la boucle pour afficher chaque fruit !',
    objective: 'Compléter la ligne manquante pour parcourir un tableau',
    difficulty: 'difficile',
    category: 'boucles',
    icon: '✏️',
    estimatedTime: '12 min',
    ageMin: 12,
    ageMax: 14
  },
  {
    id: 'complete-9',
    title: 'Complète le &&',
    description: 'Complète la condition pour vérifier deux choses à la fois !',
    objective: 'Compléter une condition avec &&',
    difficulty: 'difficile',
    category: 'logique',
    icon: '✏️',
    estimatedTime: '12 min',
    ageMin: 12,
    ageMax: 14
  },
  {
    id: 'complete-10',
    title: 'Complète l\'Objet (niveau +1)',
    description: 'Augmente le niveau d\'un joueur dans un objet !',
    objective: 'Compléter la ligne pour modifier une propriété (+= 1)',
    difficulty: 'difficile',
    category: 'variables',
    icon: '✏️',
    estimatedTime: '12 min',
    ageMin: 11,
    ageMax: 12
  },
  {
    id: 'conditions-6',
    title: 'Le Mot Secret',
    description: 'Si tu écris le bon mot… victoire !',
    objective: 'Utiliser une condition pour vérifier un mot',
    difficulty: 'facile',
    category: 'conditions',
    icon: '🕵️',
    estimatedTime: '8 min',
    ageMin: 7,
    ageMax: 8
  },
  {
    id: 'conditions-7',
    title: 'Pair ou Impair',
    description: 'Ton programme dit si un nombre est pair ou impair !',
    objective: 'Utiliser une condition avec le reste (%)',
    difficulty: 'facile',
    category: 'conditions',
    icon: '➗',
    estimatedTime: '10 min',
    ageMin: 8,
    ageMax: 9
  },
  {
    id: 'boucles-6',
    title: 'Compter de 2 en 2',
    description: 'Affiche 2, 4, 6, 8, 10 avec une boucle !',
    objective: 'Utiliser une boucle avec un pas de 2',
    difficulty: 'facile',
    category: 'boucles',
    icon: '🔢',
    estimatedTime: '8 min',
    ageMin: 8,
    ageMax: 9
  },
  {
    id: 'complete-11',
    title: 'Complète la Variable (niveau 1)',
    description: 'Complète une petite variable pour afficher un message.',
    objective: 'Compléter le bon nom de variable',
    difficulty: 'facile',
    category: 'variables',
    icon: '✏️',
    estimatedTime: '8 min',
    ageMin: 7,
    ageMax: 8
  },
  {
    id: 'complete-12',
    title: 'Complète la Concatenation',
    description: 'Complète la phrase en ajoutant le bon mot !',
    objective: 'Compléter une addition de chaînes',
    difficulty: 'facile',
    category: 'variables',
    icon: '✏️',
    estimatedTime: '8 min',
    ageMin: 6,
    ageMax: 7
  }
];

